FROM testcon:0.0
ADD ReactiveRESTfulWebServiceV2/build/libs/ReactiveRESTfulWebServiceV2-0.0.1-SNAPSHOT.jar /ReactiveRESTfulWebServiceV2-0.0.1-SNAPSHOT.jar
EXPOSE 18081
CMD java -jar /ReactiveRESTfulWebServiceV2-0.0.1-SNAPSHOT.jar
